add Row.svelte & Col.svelte
Oli8/spaper pull request #77
Opened 2023-08-04 11:42 UTC by droege

Fixes #76

2023-08-10 12:11 UTC, Oli8 requested changes

2023-08-10 12:11 UTC, Oli8 commented on src/lib/components/Layout/Col.svelte
> +﻿<div {...props}>
Use svelte class directive
```suggestion
<div {...$$restProps}
     class={classes}
     class:col-fill={fill}
     class:align-top={top}
     class:align-middle={middle}
     class:align-bottom={bottom}>
```

2023-08-10 12:11 UTC, Oli8 commented on src/lib/components/Layout/Col.svelte
> +
No blank line in props declartion, tho I understand the reasoning behind, grouping is enough for me
```suggestion
```

2023-08-10 12:11 UTC, Oli8 commented on src/lib/components/Layout/Col.svelte
> +  type colSpan = number | string | undefined;
Use null instead of undefined
```suggestion
  type colSpan = number | string | null;
```

2023-08-10 12:11 UTC, Oli8 commented on src/lib/components/Layout/Col.svelte
> +  export let lg: colSpan = undefined;
```suggestion
  export let col: colSpan = null;
  export let sm: colSpan = null;
  export let md: colSpan = null;
  export let lg: colSpan = null;
```

2023-08-10 12:11 UTC, Oli8 commented on src/lib/components/Layout/Col.svelte
> +  };
```suggestion
$: classes = `col ${$$restProps.class ?? ''} ${computeClasses(
    'col', { col, sm, md, lg }
  )}`;
```

There's an helper function in utils.ts to manage complexe classes that depends on props
Don't forget to add the import at the top
`import { computeClasses } from '../../utils';`
You will need to add the following in  `propToClass` object in utils.ts:

```
  col: (pf, val) => `${pf}-${val}`,
  sm: (_pf, val) => `sm-${val}`,
  md: (_pf, val) => `md-${val}`,
  lg: (_pf, val) => `lg-${val}`,
```

2023-08-13 15:49 UTC, droege commented
This is great, thank you for those ideas! I [applied them manually](https://github.com/Oli8/spaper/pull/77/commits/9f067e1f7cc9f7800c9c3432541bbc0f42b9e90c) so that everything (including the changes to utils.ts) can be in one commit.

2023-08-14 09:56 UTC, Oli8 approved these changes
Looking good, well done!

2023-08-16 10:06 UTC, merged